// This file was generated by liblab | https://liblab.com/

import { WebdevSdk } from 'webdev-sdk';

(async () => {
  const webdevSdk = new WebdevSdk({
    token: 'YOUR_TOKEN',
  });

  const { data } = await webdevSdk.v0.readRootV0AdminGet();

  console.log(data);
})();
