// This file was generated by liblab | https://liblab.com/

package webotodevsdk

import (
	"github.com/swagger-api/swagger-petstore/internal/configmanager"
	"github.com/swagger-api/swagger-petstore/pkg/admin"
	"github.com/swagger-api/swagger-petstore/pkg/formulas"
	"github.com/swagger-api/swagger-petstore/pkg/layouts"
	"github.com/swagger-api/swagger-petstore/pkg/meanings"
	"github.com/swagger-api/swagger-petstore/pkg/project"
	"github.com/swagger-api/swagger-petstore/pkg/properties"
	"github.com/swagger-api/swagger-petstore/pkg/values"
	"github.com/swagger-api/swagger-petstore/pkg/webotodevsdkconfig"
	"time"
)

type WebOtoDevSdk struct {
	Admin      *admin.AdminService
	Project    *project.ProjectService
	Properties *properties.PropertiesService
	Meanings   *meanings.MeaningsService
	Formulas   *formulas.FormulasService
	Values     *values.ValuesService
	Layouts    *layouts.LayoutsService
	manager    *configmanager.ConfigManager
}

func NewWebOtoDevSdk(config webotodevsdkconfig.Config) *WebOtoDevSdk {
	manager := configmanager.NewConfigManager(config)
	return &WebOtoDevSdk{
		Admin:      admin.NewAdminService(manager),
		Project:    project.NewProjectService(manager),
		Properties: properties.NewPropertiesService(manager),
		Meanings:   meanings.NewMeaningsService(manager),
		Formulas:   formulas.NewFormulasService(manager),
		Values:     values.NewValuesService(manager),
		Layouts:    layouts.NewLayoutsService(manager),
		manager:    manager,
	}
}

func (w *WebOtoDevSdk) SetBaseUrl(baseUrl string) {
	w.manager.SetBaseUrl(baseUrl)
}

func (w *WebOtoDevSdk) SetTimeout(timeout time.Duration) {
	w.manager.SetTimeout(timeout)
}

func (w *WebOtoDevSdk) SetApiKey(apiKey string) {
	w.manager.SetApiKey(apiKey)
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
