// This file was generated by liblab | https://liblab.com/

package project

type ImagineRequestParams struct {
	Target *string `queryParam:"target"`
}

func (params *ImagineRequestParams) SetTarget(target string) {
	params.Target = &target
}
