# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Formula(BaseModel):
    """Formula

    :param name: name
    :type name: str
    :param value: value, defaults to None
    :type value: str, optional
    :param form: form, defaults to None
    :type form: str, optional
    :param engine: engine, defaults to None
    :type engine: str, optional
    """

    def __init__(
        self, name: str, value: str = None, form: str = None, engine: str = None
    ):
        """Formula

        :param name: name
        :type name: str
        :param value: value, defaults to None
        :type value: str, optional
        :param form: form, defaults to None
        :type form: str, optional
        :param engine: engine, defaults to None
        :type engine: str, optional
        """
        self.name = name
        if value is not None:
            self.value = self._define_str("value", value, nullable=True)
        if form is not None:
            self.form = self._define_str("form", form, nullable=True)
        if engine is not None:
            self.engine = self._define_str("engine", engine, nullable=True)
