# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.sentinel import SENTINEL
from .validation_error import ValidationError


@JsonMap({})
class HttpValidationError(ApiError):
    """HttpValidationError

    :param detail: detail, defaults to None
    :type detail: List[ValidationError], optional
    """

    def __init__(self, detail: List[ValidationError] = SENTINEL, **kwargs):
        """HttpValidationError

        :param detail: detail, defaults to None
        :type detail: List[ValidationError], optional
        """
        if detail is not SENTINEL:
            self.detail = self._define_list(detail, ValidationError)
        self._kwargs = kwargs
