# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Meaning(BaseModel):
    """Meaning

    :param name: name
    :type name: str
    :param value: value, defaults to None
    :type value: str, optional
    """

    def __init__(self, name: str, value: str = None):
        """Meaning

        :param name: name
        :type name: str
        :param value: value, defaults to None
        :type value: str, optional
        """
        self.name = name
        if value is not None:
            self.value = self._define_str("value", value, nullable=True)
