// This file was generated by liblab | https://liblab.com/

package shared

import (
	"github.com/swagger-api/swagger-petstore/internal/clients/rest/httptransport"
)

type WebdevSdkResponse[T any] struct {
	Data     T
	Metadata WebdevSdkResponseMetadata
}

type WebdevSdkResponseMetadata struct {
	Headers    map[string]string
	StatusCode int
}

func NewWebdevSdkResponse[T any](resp *httptransport.Response[T]) *WebdevSdkResponse[T] {
	return &WebdevSdkResponse[T]{
		Data: resp.Data,
		Metadata: WebdevSdkResponseMetadata{
			StatusCode: resp.StatusCode,
			Headers:    resp.Headers,
		},
	}
}
