# This file was generated by liblab | https://liblab.com/

from web_oto_dev_sdk import WebOtoDevSdk

sdk = WebOtoDevSdk(
    api_key="YOUR_API_KEY", api_key_header="YOUR_API_KEY_HEADER", timeout=10000
)

result = sdk.admin.get_projects_admin_projects_get()

print(result)
