# This file was generated by liblab | https://liblab.com/

from webdev_sdk import WebdevSdk

sdk = WebdevSdk(access_token="YOUR_ACCESS_TOKEN", timeout=10000)

result = sdk.v0.read_root_v0_admin_get()

print(result)
