# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, List
from .utils.to_async import to_async
from ..crm_deals import CrmDealsService
from ...models import FormField


class CrmDealsServiceAsync(CrmDealsService):
    """
    Async Wrapper for CrmDealsServiceAsync
    """

    def new(self, request_body: List[FormField]) -> Awaitable[bool]:
        return to_async(super().new)(request_body)
