# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, Union
from .utils.to_async import to_async
from ..project import ProjectService
from ...models.utils.sentinel import SENTINEL
from ...models import ProjectInfo


class ProjectServiceAsync(ProjectService):
    """
    Async Wrapper for ProjectServiceAsync
    """

    def info(self) -> Awaitable[ProjectInfo]:
        return to_async(super().info)()

    def collect(self) -> Awaitable[None]:
        return to_async(super().collect)()

    def generate(self) -> Awaitable[None]:
        return to_async(super().generate)()

    def build(self) -> Awaitable[None]:
        return to_async(super().build)()

    def view(self) -> Awaitable[str]:
        return to_async(super().view)()

    def imagine(self, target: Union[str, None] = SENTINEL) -> Awaitable[None]:
        return to_async(super().imagine)(target)

    def info_1(self) -> Awaitable[ProjectInfo]:
        return to_async(super().info_1)()

    def collect_1(self) -> Awaitable[None]:
        return to_async(super().collect_1)()

    def generate_1(self) -> Awaitable[None]:
        return to_async(super().generate_1)()

    def build_1(self) -> Awaitable[None]:
        return to_async(super().build_1)()

    def view_1(self) -> Awaitable[str]:
        return to_async(super().view_1)()

    def imagine_1(self, target: Union[str, None] = SENTINEL) -> Awaitable[None]:
        return to_async(super().imagine_1)(target)
