// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { AdminService } from './services/admin';
import { ProjectService } from './services/project';
import { PropertiesService } from './services/properties';
import { MeaningsService } from './services/meanings';
import { FormulasService } from './services/formulas';
import { ValuesService } from './services/values';
import { LayoutsService } from './services/layouts';

export * from './services/admin';
export * from './services/project';
export * from './services/properties';
export * from './services/meanings';
export * from './services/formulas';
export * from './services/values';
export * from './services/layouts';
export * from './services/common';

export type * from './http';

export class WebOtoDevSdk {
  public readonly admin: AdminService;

  public readonly project: ProjectService;

  public readonly properties: PropertiesService;

  public readonly meanings: MeaningsService;

  public readonly formulas: FormulasService;

  public readonly values: ValuesService;

  public readonly layouts: LayoutsService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.admin = new AdminService(this.config);

    this.project = new ProjectService(this.config);

    this.properties = new PropertiesService(this.config);

    this.meanings = new MeaningsService(this.config);

    this.formulas = new FormulasService(this.config);

    this.values = new ValuesService(this.config);

    this.layouts = new LayoutsService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.admin.baseUrl = baseUrl;
    this.project.baseUrl = baseUrl;
    this.properties.baseUrl = baseUrl;
    this.meanings.baseUrl = baseUrl;
    this.formulas.baseUrl = baseUrl;
    this.values.baseUrl = baseUrl;
    this.layouts.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.admin.baseUrl = environment;
    this.project.baseUrl = environment;
    this.properties.baseUrl = environment;
    this.meanings.baseUrl = environment;
    this.formulas.baseUrl = environment;
    this.values.baseUrl = environment;
    this.layouts.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.admin.timeoutMs = timeoutMs;
    this.project.timeoutMs = timeoutMs;
    this.properties.timeoutMs = timeoutMs;
    this.meanings.timeoutMs = timeoutMs;
    this.formulas.timeoutMs = timeoutMs;
    this.values.timeoutMs = timeoutMs;
    this.layouts.timeoutMs = timeoutMs;
  }

  set apiKey(apiKey: string) {
    this.admin.apiKey = apiKey;
    this.project.apiKey = apiKey;
    this.properties.apiKey = apiKey;
    this.meanings.apiKey = apiKey;
    this.formulas.apiKey = apiKey;
    this.values.apiKey = apiKey;
    this.layouts.apiKey = apiKey;
  }

  set apiKeyHeader(apiKeyHeader: string) {
    this.admin.apiKeyHeader = apiKeyHeader;
    this.project.apiKeyHeader = apiKeyHeader;
    this.properties.apiKeyHeader = apiKeyHeader;
    this.meanings.apiKeyHeader = apiKeyHeader;
    this.formulas.apiKeyHeader = apiKeyHeader;
    this.values.apiKeyHeader = apiKeyHeader;
    this.layouts.apiKeyHeader = apiKeyHeader;
  }

  set projectId(projectId: string) {
    this.admin.projectId = projectId;
    this.project.projectId = projectId;
    this.properties.projectId = projectId;
    this.meanings.projectId = projectId;
    this.formulas.projectId = projectId;
    this.values.projectId = projectId;
    this.layouts.projectId = projectId;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
