// This file was generated by liblab | https://liblab.com/

package com.example;

import com.swagger.petstore.WebdevSdk;
import com.swagger.petstore.config.WebdevSdkConfig;

public class Main {

  public static void main(String[] args) {
    WebdevSdkConfig config = WebdevSdkConfig.builder().accessToken("YOUR_ACCESS_TOKEN").build();

    WebdevSdk webdevSdk = new WebdevSdk(config);

    Object response = webdevSdk.v0.readRootV0AdminGet();

    System.out.println(response);
  }
}
