// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { V0Service } from './services/v0';

export * from './services/v0';

export type * from './http';

export class WebdevSdk {
  public readonly v0: V0Service;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.v0 = new V0Service(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.v0.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.v0.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.v0.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.v0.token = token;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
