# This file was generated by liblab | https://liblab.com/

from .sdk import WebOtoDevSdk as _WebOtoDevSdk as _WebOtoDevSdk as _WebOtoDevSdk as _WebOtoDevSdk
from .sdk_async import WebOtoDevSdkAsync
from .net.environment import Environment

from .sdk_wrapper import SDKWrapper

def WebOtoDevSdk(*args, **kwargs):
    return SDKWrapper(_WebOtoDevSdk(*args, **kwargs))

from .sdk_wrapper import SDKWrapper

def WebOtoDevSdk(*args, **kwargs):
    return SDKWrapper(_WebOtoDevSdk(*args, **kwargs))

from .sdk_wrapper import SDKWrapper

def WebOtoDevSdk(*args, **kwargs):
    return SDKWrapper(_WebOtoDevSdk(*args, **kwargs))

from .sdk_wrapper import SDKWrapper

def WebOtoDevSdk(*args, **kwargs):
    return SDKWrapper(_WebOtoDevSdk(*args, **kwargs))
