// This file was generated by liblab | https://liblab.com/

package shared

import (
	"web-dev-sdk/internal/clients/rest/httptransport"
)

type WebOtoDevSdkError struct {
	Err      error
	Body     []byte
	Metadata WebOtoDevSdkErrorMetadata
}

type WebOtoDevSdkErrorMetadata struct {
	Headers    map[string]string
	StatusCode int
}

func NewWebOtoDevSdkError[T any](transportError *httptransport.ErrorResponse[T]) *WebOtoDevSdkError {
	return &WebOtoDevSdkError{
		Err:  transportError.GetError(),
		Body: transportError.GetBody(),
		Metadata: WebOtoDevSdkErrorMetadata{
			StatusCode: transportError.GetStatusCode(),
			Headers:    transportError.GetHeaders(),
		},
	}
}

func (e *WebOtoDevSdkError) Error() string {
	return e.Err.Error()
}
