// This file was generated by liblab | https://liblab.com/

package shared

import (
	"github.com/swagger-api/swagger-petstore/internal/clients/rest/httptransport"
)

type WebOtoDevSdkResponse[T any] struct {
	Data     T
	Metadata WebOtoDevSdkResponseMetadata
}

type WebOtoDevSdkResponseMetadata struct {
	Headers    map[string]string
	StatusCode int
}

func NewWebOtoDevSdkResponse[T any](resp *httptransport.Response[T]) *WebOtoDevSdkResponse[T] {
	return &WebOtoDevSdkResponse[T]{
		Data: resp.Data,
		Metadata: WebOtoDevSdkResponseMetadata{
			StatusCode: resp.StatusCode,
			Headers:    resp.Headers,
		},
	}
}
