# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .property import Property


@JsonMap({"id_": "id"})
class Project(BaseModel):
    """Project

    :param pid: pid
    :type pid: str
    :param id_: id_
    :type id_: int
    :param properties: properties, defaults to None
    :type properties: List[Property], optional
    """

    def __init__(self, pid: str, id_: int, properties: List[Property] = None):
        """Project

        :param pid: pid
        :type pid: str
        :param id_: id_
        :type id_: int
        :param properties: properties, defaults to None
        :type properties: List[Property], optional
        """
        self.pid = pid
        self.id_ = id_
        if properties is not None:
            self.properties = self._define_list(properties, Property)
