# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class PropertyUpdate(BaseModel):
    """PropertyUpdate

    :param key: key
    :type key: str
    :param value: value
    :type value: str
    """

    def __init__(self, key: str, value: str):
        """PropertyUpdate

        :param key: key
        :type key: str
        :param value: value
        :type value: str
        """
        self.key = key
        self.value = value
