# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class Property(BaseModel):
    """Property

    :param key: key
    :type key: str
    :param value: value
    :type value: str
    :param id_: id_
    :type id_: str
    :param project_id: project_id
    :type project_id: str
    """

    def __init__(self, key: str, value: str, id_: str, project_id: str):
        """Property

        :param key: key
        :type key: str
        :param value: value
        :type value: str
        :param id_: id_
        :type id_: str
        :param project_id: project_id
        :type project_id: str
        """
        self.key = key
        self.value = value
        self.id_ = id_
        self.project_id = project_id
