// This file was generated by liblab | https://liblab.com/

package meanings

type NewRequestParams struct {
	Init       *string `queryParam:"init"`
	Collection *string `queryParam:"collection"`
}

func (params *NewRequestParams) SetInit(init string) {
	params.Init = &init
}
func (params *NewRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type GetRequestParams struct {
	Name       *string `queryParam:"name" required:"true"`
	Collection *string `queryParam:"collection"`
}

func (params *GetRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *GetRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type SetRequestParams struct {
	Name       *string `queryParam:"name" required:"true"`
	Value      *string `queryParam:"value"`
	Collection *string `queryParam:"collection"`
}

func (params *SetRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *SetRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *SetRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type AddRequestParams struct {
	Name       *string `queryParam:"name" required:"true"`
	Value      *string `queryParam:"value"`
	Collection *string `queryParam:"collection"`
}

func (params *AddRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *AddRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *AddRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type AllRequestParams struct {
	Name       *string `queryParam:"name"`
	Collection *string `queryParam:"collection"`
}

func (params *AllRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *AllRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type UpdateRequestParams struct {
	Collection *string `queryParam:"collection"`
}

func (params *UpdateRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type RemoveRequestParams struct {
	Name       *string `queryParam:"name"`
	Value      *string `queryParam:"value"`
	Collection *string `queryParam:"collection"`
}

func (params *RemoveRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *RemoveRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *RemoveRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}

type DisplayRequestParams struct {
	Name       *string `queryParam:"name"`
	Collection *string `queryParam:"collection"`
	Format     *string `queryParam:"format"`
}

func (params *DisplayRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *DisplayRequestParams) SetCollection(collection string) {
	params.Collection = &collection
}
func (params *DisplayRequestParams) SetFormat(format string) {
	params.Format = &format
}
