// This file was generated by liblab | https://liblab.com/

package admin

type NewProjectRequestParams struct {
	Title    *string `queryParam:"title"`
	Slug     *string `queryParam:"slug"`
	Init     *string `queryParam:"init"`
	Internal *bool   `queryParam:"internal"`
}

func (params *NewProjectRequestParams) SetTitle(title string) {
	params.Title = &title
}
func (params *NewProjectRequestParams) SetSlug(slug string) {
	params.Slug = &slug
}
func (params *NewProjectRequestParams) SetInit(init string) {
	params.Init = &init
}
func (params *NewProjectRequestParams) SetInternal(internal bool) {
	params.Internal = &internal
}

type RemoveProjectRequestParams struct {
	Slug     *string `queryParam:"slug"`
	Uid      *string `queryParam:"uid"`
	Internal *bool   `queryParam:"internal"`
}

func (params *RemoveProjectRequestParams) SetSlug(slug string) {
	params.Slug = &slug
}
func (params *RemoveProjectRequestParams) SetUid(uid string) {
	params.Uid = &uid
}
func (params *RemoveProjectRequestParams) SetInternal(internal bool) {
	params.Internal = &internal
}

type ChangeProjectRequestParams struct {
	Slug     *string `queryParam:"slug"`
	Uid      *string `queryParam:"uid"`
	NewSlug  *string `queryParam:"new_slug"`
	NewTitle *string `queryParam:"new_title"`
	Internal *bool   `queryParam:"internal"`
}

func (params *ChangeProjectRequestParams) SetSlug(slug string) {
	params.Slug = &slug
}
func (params *ChangeProjectRequestParams) SetUid(uid string) {
	params.Uid = &uid
}
func (params *ChangeProjectRequestParams) SetNewSlug(newSlug string) {
	params.NewSlug = &newSlug
}
func (params *ChangeProjectRequestParams) SetNewTitle(newTitle string) {
	params.NewTitle = &newTitle
}
func (params *ChangeProjectRequestParams) SetInternal(internal bool) {
	params.Internal = &internal
}

type ChangeProjectSlugRequestParams struct {
	Slug     *string `queryParam:"slug"`
	Uid      *string `queryParam:"uid"`
	NewSlug  *string `queryParam:"new_slug"`
	Internal *bool   `queryParam:"internal"`
}

func (params *ChangeProjectSlugRequestParams) SetSlug(slug string) {
	params.Slug = &slug
}
func (params *ChangeProjectSlugRequestParams) SetUid(uid string) {
	params.Uid = &uid
}
func (params *ChangeProjectSlugRequestParams) SetNewSlug(newSlug string) {
	params.NewSlug = &newSlug
}
func (params *ChangeProjectSlugRequestParams) SetInternal(internal bool) {
	params.Internal = &internal
}

type ChangeProjectTitleRequestParams struct {
	Slug     *string `queryParam:"slug"`
	Uid      *string `queryParam:"uid"`
	NewTitle *string `queryParam:"new_title"`
	Internal *bool   `queryParam:"internal"`
}

func (params *ChangeProjectTitleRequestParams) SetSlug(slug string) {
	params.Slug = &slug
}
func (params *ChangeProjectTitleRequestParams) SetUid(uid string) {
	params.Uid = &uid
}
func (params *ChangeProjectTitleRequestParams) SetNewTitle(newTitle string) {
	params.NewTitle = &newTitle
}
func (params *ChangeProjectTitleRequestParams) SetInternal(internal bool) {
	params.Internal = &internal
}
