// This file was generated by liblab | https://liblab.com/

package values

type NewRequestParams struct {
	Init    *string `queryParam:"init"`
	Dataset *string `queryParam:"dataset"`
}

func (params *NewRequestParams) SetInit(init string) {
	params.Init = &init
}
func (params *NewRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type GetRequestParams struct {
	Name    *string `queryParam:"name" required:"true"`
	Dataset *string `queryParam:"dataset"`
}

func (params *GetRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *GetRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type SetRequestParams struct {
	Name    *string `queryParam:"name" required:"true"`
	Value   *string `queryParam:"value"`
	Dataset *string `queryParam:"dataset"`
}

func (params *SetRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *SetRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *SetRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type AddRequestParams struct {
	Name    *string `queryParam:"name" required:"true"`
	Value   *string `queryParam:"value"`
	Dataset *string `queryParam:"dataset"`
}

func (params *AddRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *AddRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *AddRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type AllRequestParams struct {
	Name    *string `queryParam:"name"`
	Dataset *string `queryParam:"dataset"`
}

func (params *AllRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *AllRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type UpdateRequestParams struct {
	Dataset *string `queryParam:"dataset"`
}

func (params *UpdateRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type RemoveRequestParams struct {
	Name    *string `queryParam:"name"`
	Value   *string `queryParam:"value"`
	Dataset *string `queryParam:"dataset"`
}

func (params *RemoveRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *RemoveRequestParams) SetValue(value string) {
	params.Value = &value
}
func (params *RemoveRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}

type DisplayRequestParams struct {
	Name    *string `queryParam:"name"`
	Dataset *string `queryParam:"dataset"`
	Format  *string `queryParam:"format"`
}

func (params *DisplayRequestParams) SetName(name string) {
	params.Name = &name
}
func (params *DisplayRequestParams) SetDataset(dataset string) {
	params.Dataset = &dataset
}
func (params *DisplayRequestParams) SetFormat(format string) {
	params.Format = &format
}
