# This file was generated by liblab | https://liblab.com/

from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..models.utils.cast_models import cast_models


class AdminService(BaseService):

    @cast_models
    def get_projects_admin_projects_get(self) -> any:
        """get_projects_admin_projects_get

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: Successful Response
        :rtype: any
        """

        serialized_request = (
            Serializer(f"{self.base_url}/admin/projects", self.get_default_headers())
            .serialize()
            .set_method("GET")
        )

        response = self.send_request(serialized_request)
        return response
