# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..models.utils.cast_models import cast_models
from ..models import Project


class AdminService(BaseService):

    @cast_models
    def projects(self) -> List[Project]:
        """Obtain a list of all projects [ADMIN RIGHTS REQUIRED]

        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: Successful Response
        :rtype: List[Project]
        """

        serialized_request = (
            Serializer(f"{self.base_url}/admin/projects", self.get_default_headers())
            .serialize()
            .set_method("GET")
        )

        response = self.send_request(serialized_request)
        return [Project._unmap(item) for item in response]
