// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types';
import { RequestBuilder } from '../../http/transport/request-builder';
import { SerializationStyle } from '../../http/serialization/base-serializer';
import {
  AddParams,
  AllParams,
  DisplayParams,
  Get_Params,
  New_Params,
  RemoveParams,
  Set_Params,
  UpdateParams,
} from './request-params';
import { Value, valueRequest, valueResponse } from '../common/value';

export class LayoutsService extends BaseService {
  /**
   * Create new version (default or specified settings)
   * @param {string} [init] -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async new_(params?: New_Params, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('PUT')
      .setPath('/layouts/revision/new')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'init',
        value: params?.init,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<any>(request);
  }

  /**
   * Obtain the lastest layout for page with specified 'name'
   * @param {string} name -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<string>>} Successful Response
   */
  async get_(params: Get_Params, requestConfig?: RequestConfig): Promise<HttpResponse<string>> {
    const request = new RequestBuilder<string>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/layouts/actual/get')
      .setRequestSchema(z.any())
      .setResponseSchema(z.string())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<string>(request);
  }

  /**
   * Remove all previous layouts for specified page with 'name' and add a new value
   * @param {string} name -
   * @param {string} [value] -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async set_(params: Set_Params, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('PUT')
      .setPath('/layouts/actual/set')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'value',
        value: params?.value,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<any>(request);
  }

  /**
   * Add a new value for specified page by 'name'
   * @param {string} name -
   * @param {string} [value] -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async add(params: AddParams, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('PUT')
      .setPath('/layouts/actual/add')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'value',
        value: params?.value,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<any>(request);
  }

  /**
   * Obtain a list of all layouts with specified 'name'
   * @param {string} [name] -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<Value[]>>} Successful Response
   */
  async all(params?: AllParams, requestConfig?: RequestConfig): Promise<HttpResponse<Value[]>> {
    const request = new RequestBuilder<Value[]>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/layouts/all/get')
      .setRequestSchema(z.any())
      .setResponseSchema(z.array(valueResponse))
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<Value[]>(request);
  }

  /**
   * Remove previously set and add new layouts with specified 'name' fileds with layouts from 'layouts' fileds of provided list
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async update(body: Value[], params?: UpdateParams, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('PUT')
      .setPath('/layouts/all/update')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<any>(request);
  }

  /**
   * Remove all layouts for specified 'name'
   * @param {string} [name] -
   * @param {string} [value] -
   * @param {string} [version] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async remove(params?: RemoveParams, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('DELETE')
      .setPath('/layouts/all/remove')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'value',
        value: params?.value,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .build();
    return this.client.call<any>(request);
  }

  /**
   * Display a list of all layouts with specified 'name'
   * @param {string} [name] -
   * @param {string} [version] -
   * @param {string} [format] -
   * @returns {Promise<HttpResponse<any>>} Successful Response
   */
  async display(params?: DisplayParams, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setBaseUrl(this.config)
      .setConfig(this.config)
      .setMethod('GET')
      .setPath('/layouts/all/display')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'name',
        value: params?.name,
      })
      .addQueryParam({
        key: 'version',
        value: params?.version,
      })
      .addQueryParam({
        key: 'format',
        value: params?.format,
      })
      .build();
    return this.client.call<any>(request);
  }
}
