// This file was generated by liblab | https://liblab.com/

export interface New_Params {
  init?: string;
  version?: string;
}

export interface Get_Params {
  name: string;
  version?: string;
}

export interface Set_Params {
  name: string;
  value?: string;
  version?: string;
}

export interface AddParams {
  name: string;
  value?: string;
  version?: string;
}

export interface AllParams {
  name?: string;
  version?: string;
}

export interface UpdateParams {
  version?: string;
}

export interface RemoveParams {
  name?: string;
  value?: string;
  version?: string;
}

export interface DisplayParams {
  name?: string;
  version?: string;
  format?: string;
}
