# This file was generated by liblab | https://liblab.com/

from typing import Union
from .services.admin import AdminService
from .services.control import ControlService
from .services.project import ProjectService
from .net.environment import Environment


class WebOtoDevSdk:
    def __init__(
        self,
        api_key: str = None,
        api_key_header: str = "Access-Token",
        base_url: Union[Environment, str] = Environment.DEFAULT,
        timeout: int = 60000,
    ):
        """
        Initializes WebOtoDevSdk the SDK class.
        """

        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )
        self.admin = AdminService(base_url=self._base_url)
        self.control = ControlService(base_url=self._base_url)
        self.project = ProjectService(base_url=self._base_url)
        self.set_api_key(api_key, api_key_header)
        self.set_timeout(timeout)

    def set_base_url(self, base_url: Union[Environment, str]):
        """
        Sets the base URL for the entire SDK.

        :param Union[Environment, str] base_url: The base URL to be set.
        :return: The SDK instance.
        """
        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )

        self.admin.set_base_url(self._base_url)
        self.control.set_base_url(self._base_url)
        self.project.set_base_url(self._base_url)

        return self

    def set_api_key(self, api_key: str, api_key_header="Access-Token"):
        """
        Sets the api key and the api key header for the entire SDK.
        """
        self.admin.set_api_key(api_key, api_key_header)
        self.control.set_api_key(api_key, api_key_header)
        self.project.set_api_key(api_key, api_key_header)

        return self

    def set_timeout(self, timeout: int):
        """
        Sets the timeout for the entire SDK.

        :param int timeout: The timeout (ms) to be set.
        :return: The SDK instance.
        """
        self.admin.set_timeout(timeout)
        self.control.set_timeout(timeout)
        self.project.set_timeout(timeout)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
