// This file was generated by liblab | https://liblab.com/

package com.swagger.petstore;

import com.swagger.petstore.config.WebdevSdkConfig;
import com.swagger.petstore.http.Environment;
import com.swagger.petstore.http.interceptors.DefaultHeadersInterceptor;
import com.swagger.petstore.http.interceptors.RetryInterceptor;
import com.swagger.petstore.http.interceptors.TokenInterceptor;
import com.swagger.petstore.services.V0Service;
import java.util.concurrent.TimeUnit;
import okhttp3.OkHttpClient;

public class WebdevSdk {

  public final V0Service v0;

  private final TokenInterceptor accessAuthInterceptor;

  public WebdevSdk() {
    // Default configs
    this(WebdevSdkConfig.builder().build());
  }

  public WebdevSdk(WebdevSdkConfig config) {
    final String serverUrl = config.getEnvironment().getUrl();

    this.accessAuthInterceptor =
      TokenInterceptor.builder().header("Authorization").prefix("Bearer").token(config.getAccessToken()).build();

    final OkHttpClient httpClient = new OkHttpClient.Builder()
      .addInterceptor(new DefaultHeadersInterceptor(config))
      .addInterceptor(accessAuthInterceptor)
      .addInterceptor(new RetryInterceptor(config.getRetryConfig()))
      .readTimeout(config.getTimeout(), TimeUnit.MILLISECONDS)
      .build();

    this.v0 = new V0Service(httpClient, serverUrl);
  }

  public void setEnvironment(Environment environment) {
    setBaseUrl(environment.getUrl());
  }

  public void setBaseUrl(String baseUrl) {
    this.v0.setBaseUrl(baseUrl);
  }

  public void setAccessToken(String token) {
    this.accessAuthInterceptor.setToken(token);
  }
}
// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
