// This file was generated by liblab | https://liblab.com/

package rest

import (
	"web-dev-sdk/internal/clients/rest/handlers"
	"web-dev-sdk/internal/clients/rest/hooks"
	"web-dev-sdk/internal/clients/rest/httptransport"
	"web-dev-sdk/pkg/webotodevsdkconfig"
)

type RestClient[T any] struct {
	handlers *handlers.HandlerChain[T]
}

func NewRestClient[T any](config webotodevsdkconfig.Config) *RestClient[T] {
	retryHandler := handlers.NewRetryHandler[T]()
	apiKeyHandler := handlers.NewApiKeyHandler[T]()
	responseValidationHandler := handlers.NewResponseValidationHandler[T]()
	unmarshalHandler := handlers.NewUnmarshalHandler[T]()
	requestValidationHandler := handlers.NewRequestValidationHandler[T]()
	hookHandler := handlers.NewHookHandler[T](hooks.NewDefaultHook())
	terminatingHandler := handlers.NewTerminatingHandler[T]()

	handlers := handlers.BuildHandlerChain[T]().
		AddHandler(retryHandler).
		AddHandler(apiKeyHandler).
		AddHandler(responseValidationHandler).
		AddHandler(unmarshalHandler).
		AddHandler(requestValidationHandler).
		AddHandler(hookHandler).
		AddHandler(terminatingHandler)

	return &RestClient[T]{
		handlers: handlers,
	}
}

func (client *RestClient[T]) Call(request httptransport.Request) (*httptransport.Response[T], *httptransport.ErrorResponse[T]) {
	return client.handlers.CallApi(request)
}
